id: role.surgeon
name: { ru: "Хирург" }
gen: { ru: "хирурга" }
salary: [4000, 7500]
texts:
  hint: { ru: "Оперирует в операционной вместе с анестезиологом и операционной медсестрой. Чем опытнее хирург, тем реже осложнения после операции." }
